### PR TITLE
fix(docs): Fix broken links in documentation

### PR DESCRIPTION
**Pull request by wesleyvanderlee**
Fix links in:
- dev\01-contributing.md
- config\04-preprocessors.md

### CODE REVIEW

**Comment by Moumi** [comment]
The fix with regards to _[Maintaining Karma]_ was not broken. It might seem as it needs a enumeration before it, but it does not. When the .html-files are generated for the website, they cut out the enumeration. So, no broken link there and that particular fix now will break it.

**Comment by Moumi** [comment]
Yes, that makes it work. Well, the total LGTM. If @ludai0106 and @liuyiran13 also agree, you can create a PR to the upstream! :wink:

**Comment by liuyiran13** [comment]
Good work!!!

**Comment by ludai0106** [comment]
Looks it works.  Well done!

**Comment by Moumi** [comment]
The googlebot was not pleased with the additional commit of _Merge pull request #4 from delftswa2016/update-upstream …_ which was made by me. Therefore, I created a new branch with the exact same changes and commited this PR. No need for a review as there were no other changes than in this PR.

**Pull request closed without merging**
