### PR TITLE
fix(karma): Fix issue regarding escape quotes

### PR DESCRIPTION
**Pull request by Moumi**
This PR contains the fix for issue #1876. Requires a review!

### CODE REVIEW

**Comment by ludai0106** [comment]
This seems fix the single quote issue!

**Comment by wesleyvanderlee** [comment]
Nice work :+1:, I approve this fix!

**Comment by liuyiran13** [comment]
Problem successful fixed

**Comment by Moumi** [comment]
Great! Will create PR to the Karma project.

**Pull request closed without merging**
