### PR TITLE
feat(config): Add configuration for adding javascript version.

### PR DESCRIPTION
**Pull request by Moumi**
Add the configuration to add a javascript version tag to the loaded scripts. Only applied when the Firefox browser is run.

Closes #1719

### CODE REVIEW

**Comment by Moumi** [comment]
Please pull this fix to your own computer and perform `grunt test`. Make sure that all tests pass. If not, please provide which tests fail and the errors given. Also look if additional comments are needed in the code.

**Comment by liuyiran13** [comment]
Get it , I will do the tests soon.

**Comment by wesleyvanderlee** [comment]
My tests are failing due to this error: 

> TypeError: Cannot read property 'replace' of null

Seems to me that an object is null where it isn't supposed to be. Maybe you need to place an additional check or enforce object initialization.

See [here](https://github.com/delftswa2016/karma/files/157134/test-output-03032016.txt) for full test output.

Regards,

Wesley van der Lee

**Comment by Moumi** [comment]
@wesleyvanderlee It seems that the test failures you are getting are not due to my change. Something is probably wrongly setup in your development environment.

**Comment by ludai0106** [comment]
Tests are passed with the changes !

**Comment by liuyiran13** [comment]
My test also failed because of the the reason:
> TypeError: Cannot read property 'replace' of null
It seems not because of the wrongly setup in my development environment

**Comment by liuyiran13** [comment]
My test also failed and get the error like this:

> TypeError: Cannot read property 'replace' of null

**Comment by Moumi** [comment]
Let's look into this when we are together. I might be able to help you fix your environment.

**Comment by Moumi** [comment]
This is still awaiting a proper review. Please review!

**Comment by wesleyvanderlee** [comment]
I reconfigured my environment according to [this](https://karma-runner.github.io/latest/dev/making-changes.html) site. Still get the same errors. Because everyone encounters those errors, I don't think it fully relies on the way our environment is set up. We should look together into this..

**Comment by Moumi** [comment]
@wesleyvanderlee @liuyiran13 Why not create a VM with a Linux version on it and test it out?

**Comment by Moumi** [comment]
Did not seem to `squash` the commits for this PR together, therefore I created a new PR #8. Please review that one.

This one is now closed.

**Pull request closed without merging**
