### PR TITLE
Feature javascript version tag

### PR DESCRIPTION
**Pull request by Moumi**
The javascript version tag would only be applied to the Firefox browser. This PR contains both the fix and 2 _e2e_ tests written for it. Requires review!

### CODE REVIEW

**Comment by ludai0106** [comment]
Looks fine.

**Comment by wesleyvanderlee** [comment]
lgtm :wink: 
Nice tests by the way :+1:

**Comment by liuyiran13** [comment]
Perfectly fixed the problem

**Comment by Moumi** [comment]
Great! Created a PR to the upstream for this.

**Pull request closed without merging**
