### PR TITLE
fix(docs): Fix grammar overall in .md-files

### PR DESCRIPTION
**Pull request by Moumi**
This PR contains changes made to the grammar used in the .md-files. 

Requires review!

### CODE REVIEW

**Comment by wesleyvanderlee** [comment]
looks good to me, fixes indeed the grammar mistakes.

**Comment by ludai0106** [comment]
very nice work

**Comment by liuyiran13** [comment]
Actually solved the problem

**Comment by Moumi** [comment]
Great, thanks all. I will create a PR to the upstream for our 4th PR!

**Pull request closed without merging**
