### PR TITLE
fix(updater): Fix time unit on screen display from 'ms' to 'seconds'.

### PR DESCRIPTION
**Pull request by Moumi**
In this PR is a small change that fixes issue #1936. From 'ms' to 'seconds'. Requires review!

### CODE REVIEW

**Comment by liuyiran13** [comment]
This PR fixed the time unit from 'ms' to 'seconds'.

**Comment by ludai0106** [comment]
Nice, this fixes the time unit display.

**Comment by wesleyvanderlee** [comment]
lgtm :wink:

**Comment by Moumi** [comment]
Great! Will create PR to the Karma project.

**Pull request closed without merging**
